export { default as BasicModal } from '@/common/modals/BasicModal.vue'
export { default as AuthModal } from '@/common/modals/AuthModal.vue'
export { default as CertificateModal } from '@/common/modals/CertificateModal.vue'
export { default as LoaderModal } from '@/common/modals//LoaderModal.vue'
export { default as SuccessModal } from '@/common/modals//SuccessModal.vue'
export { default as UploadTemplateModal } from '@/common/modals//UploadTemplateModal.vue'
