export { default as TemplateForm } from '@/forms/TemplateForm.vue'
export { default as SettingForm } from '@/forms/SettingForm.vue'
export { default as AuthModalForm } from '@/forms/AuthForm.vue'
export { default as MintForm } from '@/forms/MintForm.vue'
export { default as GenerationForm } from '@/forms/GenerationForm.vue'
